/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'contact-submissions': ContactSubmission;
    'email-subscribe-submissions': EmailSubscribeSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'email-subscribe-submissions': EmailSubscribeSubmissionsSelect<false> | EmailSubscribeSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    header: Header;
    footer: Footer;
    'contact-page': ContactPage;
    'product-listing-page': ProductListingPage;
    product: Product;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'product-listing-page': ProductListingPageSelect<false> | ProductListingPageSelect<true>;
    product: ProductSelect<false> | ProductSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  companyName: string;
  email: string;
  phone: string;
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribe-submissions".
 */
export interface EmailSubscribeSubmission {
  id: string;
  email: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'email-subscribe-submissions';
        value: string | EmailSubscribeSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  companyName?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-subscribe-submissions_select".
 */
export interface EmailSubscribeSubmissionsSelect<T extends boolean = true> {
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: string;
  layout?:
    | (
        | HeroBlock
        | ServicesBlock
        | CategoryBlock
        | AboutUsBlock
        | HoverMarqueeBlock
        | PopularGiftBlock
        | LogoCloudBlock
        | StepsBlock
        | TestimonialBlock
        | FaqBlock
        | FooterCtaBlock
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  title: string;
  description: string;
  link: {
    link: {
      label: string;
      href: string;
      isExternal?: boolean | null;
    };
    id?: string | null;
  }[];
  backgroundImage: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock".
 */
export interface ServicesBlock {
  services: {
    icon: string | Media;
    title: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'services';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryBlock".
 */
export interface CategoryBlock {
  heading: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'category';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsBlock".
 */
export interface AboutUsBlock {
  heading: string;
  description: string;
  link: {
    label: string;
    href: string;
    isExternal?: boolean | null;
  };
  image1: string | Media;
  image2: string | Media;
  card: {
    value: string;
    label: string;
    description: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'about-us';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HoverMarqueeBlock".
 */
export interface HoverMarqueeBlock {
  heading: string;
  link: {
    label: string;
    href: string;
    isExternal?: boolean | null;
  };
  rows: {
    label: string;
    images: (string | Media)[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'hover-marquee';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PopularGiftBlock".
 */
export interface PopularGiftBlock {
  heading: string;
  description: string;
  cards: {
    title: string;
    description: string;
    image: string | Media;
    link: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'popular-gift';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock".
 */
export interface LogoCloudBlock {
  heading: string;
  description: string;
  logos: (string | Media)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'logo-cloud';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  heading: string;
  description: string;
  steps: {
    title: string;
    description: string;
    image: string | Media;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'steps';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock".
 */
export interface TestimonialBlock {
  heading: string;
  description: string;
  image: string | Media;
  testimonials: {
    image: string | Media;
    testimonial: string;
    name: string;
    designation: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonial';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: string;
  description: string;
  link: {
    label: string;
    href: string;
    isExternal?: boolean | null;
  };
  faqs: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterCtaBlock".
 */
export interface FooterCtaBlock {
  logo: string | Media;
  heading: string;
  description: string;
  link: {
    label: string;
    href: string;
    isExternal?: boolean | null;
  };
  image1: string | Media;
  image2: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'footer-cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo: string | Media;
  navLinks: {
    link: {
      label: string;
      href: string;
      isExternal?: boolean | null;
    };
    id?: string | null;
  }[];
  offers: {
    offer: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  logo: string | Media;
  heading: string;
  socialLinks: {
    iconLink: {
      icon: string | Media;
      label: string;
      href: string;
      isExternal?: boolean | null;
    };
    id?: string | null;
  }[];
  navLinks: {
    title: string;
    links: {
      link: {
        label: string;
        href: string;
        isExternal?: boolean | null;
      };
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  contact: {
    label: string;
    link: {
      label: string;
      href: string;
      isExternal?: boolean | null;
    };
    id?: string | null;
  }[];
  policies: {
    link: {
      label: string;
      href: string;
      isExternal?: boolean | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  layout?: (SimpleHeroBlock | FormBlock | FaqBlock | FooterCtaBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleHeroBlock".
 */
export interface SimpleHeroBlock {
  title: string;
  description: string;
  backgroundImage: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'simple-hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  phone: string;
  mail: string;
  address: string;
  heading: string;
  description: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-listing-page".
 */
export interface ProductListingPage {
  id: string;
  layout?: (SimpleHeroBlock | FooterCtaBlock)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product".
 */
export interface Product {
  id: string;
  layout?: FooterCtaBlock[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        services?: T | ServicesBlockSelect<T>;
        category?: T | CategoryBlockSelect<T>;
        'about-us'?: T | AboutUsBlockSelect<T>;
        'hover-marquee'?: T | HoverMarqueeBlockSelect<T>;
        'popular-gift'?: T | PopularGiftBlockSelect<T>;
        'logo-cloud'?: T | LogoCloudBlockSelect<T>;
        steps?: T | StepsBlockSelect<T>;
        testimonial?: T | TestimonialBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        'footer-cta'?: T | FooterCtaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  link?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        id?: T;
      };
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesBlock_select".
 */
export interface ServicesBlockSelect<T extends boolean = true> {
  services?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CategoryBlock_select".
 */
export interface CategoryBlockSelect<T extends boolean = true> {
  heading?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AboutUsBlock_select".
 */
export interface AboutUsBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
      };
  image1?: T;
  image2?: T;
  card?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HoverMarqueeBlock_select".
 */
export interface HoverMarqueeBlockSelect<T extends boolean = true> {
  heading?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
      };
  rows?:
    | T
    | {
        label?: T;
        images?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PopularGiftBlock_select".
 */
export interface PopularGiftBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  cards?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogoCloudBlock_select".
 */
export interface LogoCloudBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  logos?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialBlock_select".
 */
export interface TestimonialBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  image?: T;
  testimonials?:
    | T
    | {
        image?: T;
        testimonial?: T;
        name?: T;
        designation?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterCtaBlock_select".
 */
export interface FooterCtaBlockSelect<T extends boolean = true> {
  logo?: T;
  heading?: T;
  description?: T;
  link?:
    | T
    | {
        label?: T;
        href?: T;
        isExternal?: T;
      };
  image1?: T;
  image2?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        id?: T;
      };
  offers?:
    | T
    | {
        offer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  heading?: T;
  socialLinks?:
    | T
    | {
        iconLink?:
          | T
          | {
              icon?: T;
              label?: T;
              href?: T;
              isExternal?: T;
            };
        id?: T;
      };
  navLinks?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    isExternal?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        id?: T;
      };
  policies?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              isExternal?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        'simple-hero'?: T | SimpleHeroBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        'footer-cta'?: T | FooterCtaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimpleHeroBlock_select".
 */
export interface SimpleHeroBlockSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  phone?: T;
  mail?: T;
  address?: T;
  heading?: T;
  description?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-listing-page_select".
 */
export interface ProductListingPageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        'simple-hero'?: T | SimpleHeroBlockSelect<T>;
        'footer-cta'?: T | FooterCtaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product_select".
 */
export interface ProductSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        'footer-cta'?: T | FooterCtaBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}